version: '2'
services:
  web:
    build: .
    ports:
     - "8000:8000"
    volumes:
     - .:/app
    links:
     - db

  db:
    image: mariadb
    env_file:
      - ./env_vars_mysql.txt
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - 8082:80
    env_file:
      - ./env_vars_pma.txt
    #    volumes:
#      - /sessions
