# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 14:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fieldspecs', '0001_initial'),
        ('businessareas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='E.g., ACC 450 invoicing basic', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL slug, e.g., acc-450-invoicing-basic. Auto-generated if blank.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='What this project is about. <a href="http://docutils.sourceforge.net/docs/user/rst/quickref.html" target="_new">ReStructuredText</a>')),
                ('when_created', models.DateField(auto_now=True, db_index=True)),
                ('business_area', models.ForeignKey(help_text='What business area does this project use?', on_delete=django.db.models.deletion.CASCADE, related_name='project_business_area', to='businessareas.BusinessArea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFieldSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_params', jsonfield.fields.JSONField(blank=True, default={}, help_text='JSON parameters for this setting, for this project.')),
                ('available_field_spec_setting', models.ForeignKey(help_text='Available setting the data is for.', on_delete=django.db.models.deletion.CASCADE, to='fieldspecs.AvailableFieldSetting')),
                ('project', models.ForeignKey(help_text='Project the setting data is for.', on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='UserNotionalTableSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_params', jsonfield.fields.JSONField(blank=True, default={}, help_text='JSON parameters for this setting, for this project.')),
                ('available_notional_table_setting', models.ForeignKey(help_text='Available setting the data is for.', on_delete=django.db.models.deletion.CASCADE, to='businessareas.AvailableNotionalTableSetting')),
                ('project', models.ForeignKey(help_text='Project the setting data is for.', on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='UserProjectSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_params', jsonfield.fields.JSONField(blank=True, default={}, help_text='JSON parameters for this project setting, for this project.')),
                ('available_project_setting', models.ForeignKey(help_text='Available project setting the data is for.', on_delete=django.db.models.deletion.CASCADE, to='businessareas.AvailableBusinessAreaProjectSetting')),
                ('project', models.ForeignKey(help_text='Project the setting data is for.', on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
