# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 14:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businessareas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='E.g., ACC 450 invoicing basic', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL slug, e.g., acc-450-invoicing-basic. Auto-generated if blank.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='What this project is about. <a href="http://docutils.sourceforge.net/docs/user/rst/quickref.html" target="_new">ReStructuredText</a>')),
                ('when_created', models.DateField(auto_now=True, db_index=True)),
                ('business_area', models.ForeignKey(help_text='What business area does this project use?', on_delete=django.db.models.deletion.CASCADE, related_name='project_business_area', to='businessareas.BusinessAreaDb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettingDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.TextField(default='', help_text='Machine name this setting is for.', max_length=50)),
                ('setting_params', models.TextField(blank=True, default='{}', help_text='JSON parameters for this setting, for this project.')),
                ('project', models.ForeignKey(default=0, help_text='Project the setting data is for.', on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectDb')),
            ],
        ),
    ]
