# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 15:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='E.g., ACC 450 invoicing basic', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL slug, e.g., acc-450-invoicing-basic. Auto-generated if blank.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Remind your future self what this project is about.')),
                ('created', models.DateField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
