# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettingdb',
            name='setting_params',
        ),
        migrations.AddField(
            model_name='usersettingdb',
            name='value',
            field=models.TextField(default='', help_text='Value for this setting, for this project.'),
        ),
    ]
