# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('businessareas', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableProjectSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_setting_params', jsonfield.fields.JSONField(blank=True, default={}, help_text='JSON parameters to initialize the project setting.')),
                ('business_area', models.ForeignKey(help_text='What business area is this project setting availble for?', on_delete=django.db.models.deletion.CASCADE, to='businessareas.BusinessArea')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of this setting.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of this setting.')),
                ('setting_type', models.CharField(choices=[('setting', 'Normal setting'), ('anomaly', 'Anomaly')], help_text='What type of setting is this?', max_length=10)),
                ('setting_params', jsonfield.fields.JSONField(blank=True, default={}, help_text='Parameters for this setting. JSON.')),
            ],
        ),
        migrations.CreateModel(
            name='SelectedProjectSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_params', jsonfield.fields.JSONField(blank=True, default={}, help_text='JSON parameters for this project setting, for this project.')),
                ('available_project_setting', models.ForeignKey(help_text='Available project setting the data is for.', on_delete=django.db.models.deletion.CASCADE, to='projects.AvailableProjectSetting')),
                ('project', models.ForeignKey(help_text='Project the setting data is for.', on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.AddField(
            model_name='availableprojectsetting',
            name='project_setting',
            field=models.ForeignKey(help_text='The project setting that is available.', on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectSetting'),
        ),
    ]
