# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20170810_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='What this project is about. <a href="http://docutils.sourceforge.net/docs/user/rst/quickref.html" target="_new">ReStructuredText</a>'),
        ),
        migrations.AlterField(
            model_name='project',
            name='when_created',
            field=models.DateField(auto_now=True, db_index=True),
        ),
    ]
