# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20170814_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_params',
        ),
    ]
