# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryKeyAnomaly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of this anomaly.', max_length=200)),
                ('description', models.TextField(blank=True, help_text=' of this anomaly.')),
                ('pk_can_be_zero', models.BooleanField(default=False, help_text='The primary key can be zero for some records.')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
