# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of this anomaly.', max_length=200)),
                ('description', models.TextField(blank=True, help_text=' of this anomaly.')),
                ('anomaly_params', models.TextField(blank=True, help_text='Parameters for this anomaly. JSON.')),
            ],
        ),
        migrations.DeleteModel(
            name='PrimaryKeyAnomaly',
        ),
    ]
