# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalies', '0002_auto_20170810_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomaly',
            name='description',
            field=models.TextField(blank=True, help_text='Description of this anomaly.'),
        ),
    ]
