# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldSettingDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of this setting.', max_length=200)),
                ('machine_name', models.TextField(default='', help_text='Machine name of this setting, e.g., quantity.', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of this setting.')),
                ('setting_group', models.CharField(choices=[('setting', 'Basic setting'), ('anomaly', 'Anomaly')], default='setting', help_text='What setting is this? Basic setting, or anomaly.', max_length=10)),
                ('setting_type', models.CharField(choices=[('daterange', 'Date range (start and end)'), ('boolean', 'Boolean (on or off)'), ('int', 'Integer'), ('choice', 'Choice from a list'), ('currency', 'Currency'), ('float', 'Float')], help_text='What type of setting is this?', max_length=20)),
                ('setting_params', models.TextField(blank=True, default='{}', help_text='Parameters for this setting. JSON.')),
            ],
        ),
    ]
