# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldsettings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldsettingdb',
            name='setting_type',
            field=models.CharField(choices=[('date', 'A date'), ('boolean', 'Boolean (on or off)'), ('int', 'Integer'), ('choice', 'Choice from a list'), ('currency', 'Currency'), ('float', 'Float')], help_text='What type of setting is this?', max_length=20),
        ),
    ]
