# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(help_text='Your name', max_length=50, verbose_name='Your name')),
                ('contact_email', models.EmailField(help_text='Your email address', max_length=254, verbose_name='Your email')),
                ('message', models.TextField(help_text='What do you want to say?', max_length=10000)),
                ('when_sent', models.DateField(auto_now=True, db_index=True)),
            ],
        ),
    ]
