# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactformmessage_when_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactformmessage',
            old_name='email',
            new_name='contact_email',
        ),
        migrations.RenameField(
            model_name='contactformmessage',
            old_name='name',
            new_name='contact_name',
        ),
    ]
