# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20170812_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmessage',
            name='when_sent',
            field=models.DateField(auto_now=True, db_index=True),
        ),
    ]
