# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fieldsettings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableBusinessAreaProjectSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_setting_params', jsonfield.fields.JSONField(blank=True, default={}, help_text='JSON parameters to initialize the project setting.')),
            ],
        ),
        migrations.CreateModel(
            name='AvailableNotionalTableSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_setting_order', models.IntegerField(default=1, help_text='Order of the setting in the settings list for the field.')),
                ('table_setting_params', jsonfield.fields.JSONField(blank=True, default={}, help_text='JSON parameters to initialize the table setting.')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='E.g., Invoicing.', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('available_business_area_project_settings', models.ManyToManyField(help_text='Settings projects for this business area can have.', through='businessareas.AvailableBusinessAreaProjectSetting', to='fieldsettings.FieldSetting')),
            ],
        ),
        migrations.CreateModel(
            name='NotionalTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='E.g., Customers.', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('available_table_settings', models.ManyToManyField(help_text='Settings that this table can have.', related_name='available_table_settings', through='businessareas.AvailableNotionalTableSetting', to='fieldsettings.FieldSetting')),
                ('business_area', models.ForeignKey(help_text='What business area is this notional table part of?', on_delete=django.db.models.deletion.CASCADE, related_name='notional_table_business_area', to='businessareas.BusinessArea')),
            ],
        ),
        migrations.AddField(
            model_name='availablenotionaltablesetting',
            name='table',
            field=models.ForeignKey(help_text='Notional table can have the setting.', on_delete=django.db.models.deletion.CASCADE, to='businessareas.NotionalTable'),
        ),
        migrations.AddField(
            model_name='availablenotionaltablesetting',
            name='table_setting',
            field=models.ForeignKey(help_text='A setting the notional table can have.', on_delete=django.db.models.deletion.CASCADE, to='fieldsettings.FieldSetting'),
        ),
        migrations.AddField(
            model_name='availablebusinessareaprojectsetting',
            name='business_area',
            field=models.ForeignKey(help_text='What business area is this project setting available for?', on_delete=django.db.models.deletion.CASCADE, to='businessareas.BusinessArea'),
        ),
        migrations.AddField(
            model_name='availablebusinessareaprojectsetting',
            name='project_setting',
            field=models.ForeignKey(help_text='The setting that is available.', on_delete=django.db.models.deletion.CASCADE, to='fieldsettings.FieldSetting'),
        ),
    ]
