# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='E.g., Invoicing.', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('default_params', models.TextField(blank=True, help_text='Default parameters for this business area. JSON.')),
            ],
        ),
        migrations.CreateModel(
            name='NotionalTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='E.g., Customers.', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('business_area', models.ForeignKey(help_text='What business area is this notional table part of?', on_delete=django.db.models.deletion.CASCADE, related_name='business_area', to='businessareas.BusinessArea')),
            ],
        ),
    ]
