# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fieldsettings', '0003_auto_20170816_1606'),
        ('businessareas', '0002_remove_businessarea_default_params'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableNotionalTableSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_setting_order', models.IntegerField(default=1, help_text='Order of the setting in the settings list for the field.')),
                ('table_setting_params', jsonfield.fields.JSONField(blank=True, default={}, help_text='JSON parameters to initialize the table setting.')),
                ('table', models.ForeignKey(help_text='Notional table can have the setting.', on_delete=django.db.models.deletion.CASCADE, to='businessareas.NotionalTable')),
                ('table_setting', models.ForeignKey(help_text='A setting the notional table can have.', on_delete=django.db.models.deletion.CASCADE, to='fieldsettings.FieldSetting')),
            ],
        ),
        migrations.AddField(
            model_name='notionaltable',
            name='available_table_settings',
            field=models.ManyToManyField(help_text='Settings that this table can have.', related_name='available_table_settings', through='businessareas.AvailableNotionalTableSetting', to='fieldsettings.FieldSetting'),
        ),
    ]
