# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fieldspecs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldspec',
            name='field_spec_params',
        ),
    ]
