# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldspecs', '0002_remove_fieldspec_field_spec_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablefieldsetting',
            name='field_setting_order',
            field=models.IntegerField(default=1, help_text='Order of the setting in the settings list for the field.'),
        ),
    ]
