# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldsettings', '0002_auto_20170815_2004'),
        ('fieldspecs', '0003_availablefieldsetting_field_setting_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldspec',
            name='possible_field_settings',
        ),
        migrations.AddField(
            model_name='fieldspec',
            name='available_field_settings',
            field=models.ManyToManyField(help_text='Settings that this field specification can have.', related_name='available_settings', through='fieldspecs.AvailableFieldSetting', to='fieldsettings.FieldSetting'),
        ),
    ]
