# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Page title, e.g., "Owls like vegemite". Plain text.', max_length=50)),
                ('slug', models.SlugField(help_text='Friendly URL of the page, e.g., "/owls-like-vegemite". Lowercase, digits, and -.', unique=True)),
                ('content', models.TextField(blank=True, help_text='Page content. <a href="http://docutils.sourceforge.net/docs/user/rst/quickref.html" target="_blank">ReStructuredText</a>.')),
                ('status', models.CharField(choices=[('published', 'Published'), ('blocked', 'Blocked')], default='published', max_length=12)),
                ('when_created', models.DateTimeField(editable=False)),
                ('when_updated', models.DateTimeField(editable=False)),
                ('needs_work', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Notes for editors. <a href="http://docutils.sourceforge.net/docs/user/rst/quickref.html" target="_blank">ReStructuredText</a>.')),
            ],
        ),
    ]
