# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepage',
            name='slug',
            field=models.SlugField(help_text='Friendly URL of the page, e.g., "owls-like-vegemite". Lowercase, digits, and -.', unique=True),
        ),
        migrations.AlterField(
            model_name='sitepage',
            name='when_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sitepage',
            name='when_updated',
            field=models.DateTimeField(),
        ),
    ]
