# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-06 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0002_auto_20170713_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitepage',
            name='when_created',
        ),
        migrations.RemoveField(
            model_name='sitepage',
            name='when_updated',
        ),
        migrations.AlterField(
            model_name='sitepage',
            name='content',
            field=models.TextField(blank=True, help_text='Page content. <a href="https://daringfireball.net/projects/markdown/syntax" target="_blank">Markdown</a>.'),
        ),
        migrations.AlterField(
            model_name='sitepage',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes for editors. <a href="https://daringfireball.net/projects/markdown/syntax" target="_blank">Markdown</a>.'),
        ),
    ]
