# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0003_auto_20170806_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepage',
            name='content',
            field=models.TextField(blank=True, help_text='Page content. <a href="">reStructuredText Quick Reference</a>'),
        ),
        migrations.AlterField(
            model_name='sitepage',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes for editors. <a href="">reStructuredText Quick Reference</a>.'),
        ),
    ]
