# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldsettings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldsetting',
            name='setting_group',
            field=models.CharField(choices=[('setting', 'Basic setting'), ('anomaly', 'Anomaly')], default='setting', help_text='What setting is this? Basic setting, or anomaly.', max_length=10),
        ),
        migrations.AlterField(
            model_name='fieldsetting',
            name='setting_type',
            field=models.CharField(choices=[('daterange', 'Date range (start and end)'), ('boolean', 'Boolean (on or off)')], help_text='What type of setting is this?', max_length=20),
        ),
    ]
