# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldsettings', '0002_auto_20170815_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldsetting',
            name='setting_type',
            field=models.CharField(choices=[('daterange', 'Date range (start and end)'), ('boolean', 'Boolean (on or off)'), ('int', 'Integer')], help_text='What type of setting is this?', max_length=20),
        ),
    ]
